[[bin]]
name="00hello"
start="0x80400000"
end="0x80420000"
file="target/riscv64gc-unknown-none-elf/release/00hello.bin"

[[bin]]
name="01print_stack"
start="0x80420000"
end="0x80440000"
file="target/riscv64gc-unknown-none-elf/release/01print_stack.bin"

[[bin]]
name="02sleep"
start="0x80440000"
end="0x80460000"
file="target/riscv64gc-unknown-none-elf/release/02sleep.bin"

[[bin]]
name="03priv_inst"
start="0x80460000"
end="0x80480000"
file="target/riscv64gc-unknown-none-elf/release/03priv_inst.bin"

[[bin]]
name="04csr"
start="0x80480000"
end="0x804a0000"
file="target/riscv64gc-unknown-none-elf/release/04csr.bin"

