name: os

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: env
      run: rustup default nightly && rustup target add riscv64gc-unknown-none-elf && cargo install cargo-binutils && rustup component add llvm-tools
    - name: Build
      run: make build
      working-directory: ./os
